#!/bin/sh

set -e

bundler install
bundler exec jekyll build
ruby sitemap.rb
rm -rf htmltest
mkdir -p htmltest
# our baseUrl is /docs so we need to create that structure for htmltest
# otherwise it would fail to find absolute links like /docs/3.9
cp -a _site htmltest/docs
# do not deploy file generated by jekyll-redirect-from v0.13.0+ plugin
rm -f htmltest/docs/redirects.json
htmltest
(cd htmltest && tar cvzf docs.tar.gz docs)
