#!/bin/sh

set -e

bundler install
bundler exec jekyll build
ruby sitemap.rb
# do not deploy file generated by jekyll-redirect-from v0.13.0+ plugin
rm -f _site/docs/redirects.json
htmltest

rm -rf htmltest
mkdir -p htmltest
(cd _site && tar cvzf ../htmltest/docs.tar.gz docs)
