#!/usr/bin/env ruby

# This script adjusts the generated output of
# > oasisctl --generate-docs --replace-underscore
#
# - Replace underscore with hyphen in file names
# - Fix headline levels (start at <h1>)
# - Titel case for main headline
# - No all upper-case headlines ("## SEE ALSO")
# - Remove "###### Auto generated by spf13/cobra on dd-mmm-yyyy"
#
# Usage:
# ruby oasisctl.rb /path/to/generated-docs /path/to/x.x/oasis
#
# Prints navigation definition entries to stdout

require 'pathname'

def main()
    if ARGV.length < 2
        puts "Usage:\nruby #{File.basename(__FILE__)} <source-dir> <target-dir>"
        exit 1
    end

    inpath = Pathname.new(ARGV[0]).cleanpath
    outpath = Pathname.new(ARGV[1]).cleanpath

    [inpath, outpath].each { |dir|
        if not Dir.exist?(dir)
            raise IOError, "Directory does not exist: #{dir}"
        end
    }

    Dir.glob(File.join(inpath, "oasisctl*.md")).each { |infile|
        base = File.basename(infile)
        outfile = File.join(outpath, base.gsub('_', '-'))
        rewrite_content(infile, outfile)
        title_arr = File.basename(infile, '.md').split('_')
        title = "Oasisctl"
        if title_arr.length > 1
            title = title_arr[1..].map{|word| word.capitalize}.join(' ')
        end
        # Output for pasting into x.x-oasis.yml navigation definition
        puts "    - text: #{title}\n      href: #{File.basename(outfile, '.md') + '.html'}"
    }
end

def rewrite_content(infile, outfile)
    lines = File.readlines(infile)
    f = File.open(outfile, "w")
    lines.each { |line|
        if line.start_with?("###### Auto generated")
            # ignore
        elsif line.start_with?("## ")
            # Capitalize first letter of each word in main headline
            f.write(line[1..].split(" ").map{|word| word.capitalize}.join(" ") + "\n")
        elsif line == "### SEE ALSO\n"
            f.write("## See also\n")
        elsif line.start_with?("### ")
            f.write(line[1..])
        # Monkey-patching frontmatter (TODO: port to oasisctl?)
        elsif line.start_with?("description: ")
            f.write("description: Command-line client tool for managing ArangoDB Oasis\n")
        elsif line.start_with?("title: ")
            f.write("title: ArangoDB Oasis Shell oasisctl\n")
        else
            f.write(line)
        end
    }
    f.close()
end

main()
